[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "Q",
    "B",
    "ASYNC",
]

ignore = [
    "E501",
    "B003",
    "B007",
    "B009",
    "B010",
    "B904",
    "B018",
]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[format]
quote-style = "single"

[lint.flake8-bugbear]
extend-immutable-calls = ["Depends", "fastapi.Depends", "fastapi.params.Depends"]
