exclude = [
    "agenthub/monologue_agent/regression/",
]

[lint]
select = [
    "E",
    "W",
    "F",
    "I"
    "Q",
]

ignore = [
    "E501",
]

flake8-quotes = {inline-quotes = "single"}

[format]
quote-style = "single"
